### ISSUE TITLE
add button to center on gps

### ISSUE THREAD

**Issue by infinitel8p** [infinitel8p/Topspot#11]
https://kivymd.readthedocs.io/en/latest/components/button/#mdfloatingactionbutton

**Comment by infinitel8p** [comment]
added  following changes to main.kv
```           
          AnchorLayout:
              anchor_x: 'right'
              anchor_y: 'bottom'
              padding: dp(20), dp(30)

              MDFloatingActionButton:
                  icon: "crosshairs-gps"
                  md_bg_color: app.theme_cls.primary_color
                  on_release: GpsHelper.gps_button_callback()
```
