### ISSUE TITLE
add geocoordinates to bottom screen

### ISSUE THREAD

**Issue by infinitel8p** [infinitel8p/Topspot#9]
#gps coordinates status label
        self.status_label = MDLabel(
            halign="right",
            theme_text_color = "Hint",
            pos_hint = {"center_x": 0.485, 'center_y': 0.05},
            text = "Checking GPS...",
            #font_size = 12,
            font_style = "Caption"
            )
        screen.add_widget(self.status_label)

        f"Seeing: {self.get_bbox()}"
        f"Spots in FOV: {len(spots)}"

        gps.configure(on_location = self.update_blinker_position, on_status = self.on_auth_status)
        gps.start(minTime = 1000, minDistance = 0)

    def update_blinker_position(self, *args, **kwargs):
        my_lat = kwargs["lat"]
        my_lon = kwargs["lon"]
        self.status_label.text = "GPS Position:", my_lat, my_lon

Add something like this

**Comment by infinitel8p** [comment]
added following changes

 - main.kv:
```
        AnchorLayout:
            anchor_x: 'left'
            anchor_y: 'bottom'
            padding: dp(10), dp(0)

            MDLabel:
                id: coordinate_label
                text: "GPS Coordinates:\nlat:\nlon:"
                size_hint: None, None
                font_style: "Caption"
                theme_text_color: "Hint"
``` 

 - gpshelper.py:
 ```
        #update gps coordinates on screen
        if platform == "android" or platform == "ios":
            coordinate_label = MDApp.get_running_app().root.ids.coordinate_label
            coordinate_label.text = f"GPS Coordinates:\nlat: {round(my_lat, 5)}\nlon: {round(my_lon, 5)}"
```

 - topspotmap.py
 ```
        #update gps coordinates on screen
        if platform == "android" or platform == "ios":
            pass
        else:
            #update gps coordinates on screen
            coordinate_label = MDApp.get_running_app().root.ids.coordinate_label
            coordinate_label.text = f"GPS Coordinates:\nlat: {round((min_lat+max_lat)/2, 5)}\nlon: {round((min_lon+max_lon)/2, 5)}"
```
